//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema";
import type { FindManyArgs as $FindManyArgs, FindUniqueArgs as $FindUniqueArgs, FindFirstArgs as $FindFirstArgs, ExistsArgs as $ExistsArgs, CreateArgs as $CreateArgs, CreateManyArgs as $CreateManyArgs, CreateManyAndReturnArgs as $CreateManyAndReturnArgs, UpdateArgs as $UpdateArgs, UpdateManyArgs as $UpdateManyArgs, UpdateManyAndReturnArgs as $UpdateManyAndReturnArgs, UpsertArgs as $UpsertArgs, DeleteArgs as $DeleteArgs, DeleteManyArgs as $DeleteManyArgs, CountArgs as $CountArgs, AggregateArgs as $AggregateArgs, GroupByArgs as $GroupByArgs, WhereInput as $WhereInput, SelectInput as $SelectInput, IncludeInput as $IncludeInput, OmitInput as $OmitInput, UncheckedCreateInput as $UncheckedCreateInput, CheckedCreateInput as $CheckedCreateInput, UncheckedUpdateInput as $UncheckedUpdateInput, CheckedUpdateInput as $CheckedUpdateInput, QueryOptions as $QueryOptions } from "@zenstackhq/orm";
import type { SimplifiedPlainResult as $Result, SelectIncludeOmit as $SelectIncludeOmit } from "@zenstackhq/orm";
export type GalleryFindManyArgs = $FindManyArgs<$Schema, "Gallery">;
export type GalleryFindUniqueArgs = $FindUniqueArgs<$Schema, "Gallery">;
export type GalleryFindFirstArgs = $FindFirstArgs<$Schema, "Gallery">;
export type GalleryExistsArgs = $ExistsArgs<$Schema, "Gallery">;
export type GalleryCreateArgs = $CreateArgs<$Schema, "Gallery">;
export type GalleryCreateManyArgs = $CreateManyArgs<$Schema, "Gallery">;
export type GalleryCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "Gallery">;
export type GalleryUpdateArgs = $UpdateArgs<$Schema, "Gallery">;
export type GalleryUpdateManyArgs = $UpdateManyArgs<$Schema, "Gallery">;
export type GalleryUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "Gallery">;
export type GalleryUpsertArgs = $UpsertArgs<$Schema, "Gallery">;
export type GalleryDeleteArgs = $DeleteArgs<$Schema, "Gallery">;
export type GalleryDeleteManyArgs = $DeleteManyArgs<$Schema, "Gallery">;
export type GalleryCountArgs = $CountArgs<$Schema, "Gallery">;
export type GalleryAggregateArgs = $AggregateArgs<$Schema, "Gallery">;
export type GalleryGroupByArgs = $GroupByArgs<$Schema, "Gallery">;
export type GalleryWhereInput = $WhereInput<$Schema, "Gallery">;
export type GallerySelect = $SelectInput<$Schema, "Gallery">;
export type GalleryInclude = $IncludeInput<$Schema, "Gallery">;
export type GalleryOmit = $OmitInput<$Schema, "Gallery">;
export type GalleryUncheckedCreateInput = $UncheckedCreateInput<$Schema, "Gallery">;
export type GalleryCheckedCreateInput = $CheckedCreateInput<$Schema, "Gallery">;
export type GalleryUncheckedUpdateInput = $UncheckedUpdateInput<$Schema, "Gallery">;
export type GalleryCheckedUpdateInput = $CheckedUpdateInput<$Schema, "Gallery">;
export type GalleryGetPayload<Args extends $SelectIncludeOmit<$Schema, "Gallery", true>, Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>> = $Result<$Schema, "Gallery", Args, Options>;
