// This file is generated by zenstack-orpc. Do not edit.

export const fileFields = {
  "Gallery": {
    "photos": {
      "accept": [
        "image/*"
      ],
      "multiple": true
    }
  }
} as const

export type FileFields = typeof fileFields

/** `///` comments of models and fields (OpenAPI descriptions). */
export const docs = {
  "Gallery": {
    "fields": {
      "photos": "Several files: `gallery.photos.upload` appends one."
    }
  }
} as const
