//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { schema as $schema, type SchemaType as $Schema } from "./schema";
import type { ModelResult as $ModelResult, TypeDefResult as $TypeDefResult } from "@zenstackhq/orm";
export type User = $ModelResult<$Schema, "User">;
export type Profile = $ModelResult<$Schema, "Profile">;
export type Post = $ModelResult<$Schema, "Post">;
/**
 * Deleted with its post (and its post's author), files included.
 */
export type Attachment = $ModelResult<$Schema, "Attachment">;
export type Todo = $ModelResult<$Schema, "Todo">;
export type Tag = $ModelResult<$Schema, "Tag">;
/**
 * Polymorphic base model (`@@delegate`): rows live in `Asset` and in the sub-model's table.
 */
export type Asset = $ModelResult<$Schema, "Asset">;
export type Video = $ModelResult<$Schema, "Video">;
export type Image = $ModelResult<$Schema, "Image">;
/**
 * Database view (created by a migration, not by `$pushSchema`): read-only.
 */
export type PostStats = $ModelResult<$Schema, "PostStats">;
export type Address = $TypeDefResult<$Schema, "Address">;
export const Role = $schema.enums.Role.values;
export type Role = (typeof Role)[keyof typeof Role];
