// This file is generated by zenstack-orpc. Do not edit.

export const fileFields = {
  "User": {
    "avatar": {
      "accept": [
        "image/*"
      ],
      "maxSize": 1048576
    }
  },
  "Post": {
    "cover": {
      "accept": [
        "image/png",
        "image/jpeg"
      ],
      "maxSize": 1048576
    },
    "archive": {}
  },
  "Attachment": {
    "file": {},
    "thumbnail": {}
  },
  "Asset": {
    "preview": {}
  },
  "Video": {
    "preview": {},
    "source": {
      "accept": [
        "video/*"
      ]
    }
  },
  "Image": {
    "preview": {}
  }
} as const

export type FileFields = typeof fileFields

/** `///` comments of models and fields (OpenAPI descriptions). */
export const docs = {
  "User": {
    "fields": {
      "postCount": "Number of posts, computed by the database (`computedFields` of the client)."
    }
  },
  "Post": {
    "fields": {
      "archive": "Kept in storage when the post is deleted or the field changes."
    }
  },
  "Attachment": {
    "description": "Deleted with its post (and its post's author), files included.",
    "fields": {
      "thumbnail": "Kept in storage, even when a cascade deletes the attachment."
    }
  },
  "Todo": {
    "fields": {
      "title": "Overridden by `@meta('description')`."
    }
  },
  "Asset": {
    "description": "Polymorphic base model (`@@delegate`): rows live in `Asset` and in the sub-model's table.",
    "fields": {
      "preview": "Deleted with the asset, from whichever model the asset is deleted."
    }
  },
  "Video": {
    "fields": {
      "preview": "Deleted with the asset, from whichever model the asset is deleted."
    }
  },
  "Image": {
    "fields": {
      "preview": "Deleted with the asset, from whichever model the asset is deleted."
    }
  },
  "PostStats": {
    "description": "Database view (created by a migration, not by `$pushSchema`): read-only."
  }
} as const
