import type {
  AsyncIteratorClass,
  Builder,
  BuilderWithMiddlewares,
  Context,
  Procedure,
  Schema,
} from '@orpc/server'
import type { GetModels, SchemaDef } from '@zenstackhq/orm/schema'
import type { ChangeBatch } from '../live/events'
import type { TopicValue } from '../live/topics'
import type { CrudOperation } from '../operations'
import type { TransactionOperation } from '../transaction'
import type { DefaultOperationResult, ModelOperation, OperationInput } from './operations'

/** Initial context of a builder (`os.$context<Ctx>()...`). */
export type InferInitialContext<B> =
  B extends Builder<infer I, any>
    ? I
    : B extends BuilderWithMiddlewares<infer I, any, any>
      ? I
      : Context

/** Context received by handlers of a builder (initial & injected by middlewares). */
export type InferCurrentContext<B> =
  B extends Builder<infer I, any>
    ? I
    : B extends BuilderWithMiddlewares<infer I, infer C, any>
      ? Omit<I, keyof C> & C
      : Context

export type ZenStackProcedure<
  TInitial extends Context,
  TCurrent extends Context,
  TIn,
  TOut,
> = Procedure<TInitial, TCurrent, Schema<TIn, TIn>, Schema<TOut, TOut>, Record<never, never>>

/** Procedures generated for one model. */
export type ZenStackModelRouter<
  S extends SchemaDef,
  M extends GetModels<S>,
  TInitial extends Context,
  TCurrent extends Context,
  Ops extends CrudOperation = CrudOperation,
> = {
  [Op in Ops]: ZenStackProcedure<
    TInitial,
    TCurrent,
    OperationInput<S, M, Op>,
    DefaultOperationResult<S, M, Op>
  >
}

export type TransactionProcedure<
  TInitial extends Context,
  TCurrent extends Context,
> = ZenStackProcedure<TInitial, TCurrent, TransactionOperation[], unknown[]>

/** Input of the `$changes` procedure: the topics to watch (see `queryTopics`). */
export type ChangesInput<S extends SchemaDef> = {
  topics: { model: GetModels<S>; field?: string; value?: TopicValue }[]
}

export type ChangesProcedure<
  S extends SchemaDef,
  TInitial extends Context,
  TCurrent extends Context,
> = Procedure<
  TInitial,
  TCurrent,
  Schema<ChangesInput<S>, ChangesInput<S>>,
  Schema<AsyncIterator<ChangeBatch>, AsyncIteratorClass<ChangeBatch>>,
  Record<never, never>
>

type SelectModels<S extends SchemaDef, Filter> = Filter extends {
  include: readonly (infer I extends GetModels<S>)[]
}
  ? Filter extends { exclude: readonly (infer E extends GetModels<S>)[] }
    ? Exclude<I, E>
    : I
  : Filter extends { exclude: readonly (infer E extends GetModels<S>)[] }
    ? Exclude<GetModels<S>, E>
    : GetModels<S>

type SelectOperations<Filter> = Filter extends {
  include: readonly (infer I extends CrudOperation)[]
}
  ? Filter extends { exclude: readonly (infer E extends CrudOperation)[] }
    ? Exclude<I, E>
    : I
  : Filter extends { exclude: readonly (infer E extends CrudOperation)[] }
    ? Exclude<CrudOperation, E>
    : CrudOperation

/**
 * Router generated by `createZenStackRouter`. Its procedures have non-generic inputs/outputs
 * (the default result of each operation), which keeps type-checking fast and lets the router be
 * nested anywhere. Use `@azzerty23/zenstack-orpc/client` or `@azzerty23/zenstack-orpc/tanstack-query` on the client for
 * results inferred from `select` / `include` / `omit`.
 */
export type ZenStackRouter<
  S extends SchemaDef,
  TInitial extends Context = Context,
  TCurrent extends Context = TInitial,
  Options = {},
> = {
  [M in SelectModels<
    S,
    Options extends { models: infer F } ? F : {}
  > as Uncapitalize<M>]: ZenStackModelRouter<
    S,
    M,
    TInitial,
    TCurrent,
    SelectOperations<Options extends { operations: infer F } ? F : {}> & ModelOperation<S, M>
  >
} & (Options extends { transaction: false }
  ? {}
  : { $transaction: TransactionProcedure<TInitial, TCurrent> }) &
  (Options extends { live: object } ? { $changes: ChangesProcedure<S, TInitial, TCurrent> } : {})
