import type { AnyNestedClient } from '@orpc/client'
import {
  createTanstackQueryUtils,
  type RouterUtils,
  type RouterUtilsOptions,
} from '@orpc/tanstack-query'
import type { QueryClient } from '@tanstack/query-core'
import type { SchemaDef } from '@zenstackhq/orm/schema'
import type { ApplyTyped, TypedDescriptor, WithZenStack } from '../client'
import type { FileFieldsDef } from '../files/schema'
import { withTransactionCallbacks } from '../transaction-callback'
import {
  type ZenStackQueryPlugin,
  type ZenStackQueryPluginOptions,
  zenstackQueryPlugin,
} from './plugin'

export { getAllQueries, getZenStackQueries, invalidateMatching } from './cache'
export { zenstackHydration } from './hydration'
export { parseOperationKey } from './keys'
export { LIVE_META_KEY, LiveManager, type LiveManagerOptions, type LiveQueryMeta } from './live'
export { type AuthProvider, type AuthUser, completeOptimisticData } from './optimistic'
export { type PaginationMode, paginate, type ZenStackPageParam } from './pagination'
export { ZenStackQueryPlugin, type ZenStackQueryPluginOptions, zenstackQueryPlugin } from './plugin'
export type * from './types'

const PLUGINS = new WeakMap<object, ZenStackQueryPlugin<any>>()

/**
 * Starts the live updates of a `QueryClient` right away, and returns a function stopping them.
 *
 * Live queries normally connect when they first fetch. Queries hydrated from the server (SSR,
 * server components) don't fetch, so connect the browser's `QueryClient` explicitly:
 *
 * ```tsx
 * useEffect(() => connectLive(orpc, queryClient), [queryClient])
 * ```
 */
export function connectLive(utils: object, queryClient: QueryClient): () => void {
  const plugin = PLUGINS.get(utils)
  if (!plugin) throw new Error('connectLive expects utils created by createZenStackQueryUtils')
  plugin.liveManager(queryClient)
  return () => plugin.disposeLive(queryClient)
}

/** Types TanStack Query utils (`createTanstackQueryUtils`) with inferred ZenStack results. */
export interface WithQueryUtils<Z extends WithZenStack<any, any, any>> extends TypedDescriptor {
  readonly __kind: 'query-utils'
  readonly __zenstack: Z
}

export interface ZenStackQueryUtilsOptions<
  TClient extends AnyNestedClient,
  S extends SchemaDef,
  Path extends string,
  Files,
> extends Omit<RouterUtilsOptions<TClient>, 'path'>,
    Pick<ZenStackQueryPluginOptions, 'invalidate' | 'optimistic' | 'live' | 'logging' | 'auth'> {
  /** The ZenStack schema (`schema` from the generated `schema.ts`). */
  schema: S
  /** Where the ZenStack router is mounted in the app router (dotted for nested routers). */
  path: Path
  /** `fileFields` from the `orpc.ts` file generated by the zenstack-orpc ZenStack plugin. */
  files?: Files
}

/**
 * Creates TanStack Query utils for an oRPC client (like `createTanstackQueryUtils`), with:
 * - results inferred from `select` / `include` / `omit`;
 * - automatic invalidation of affected queries after mutations;
 * - optional optimistic updates;
 * - live queries (`liveOptions`) refreshed from the `$changes` stream.
 *
 * @example
 * ```ts
 * export const orpc = createZenStackQueryUtils(client, { schema, path: 'db', optimistic: true })
 * useQuery(orpc.db.post.findMany.liveOptions({ input: { include: { author: true } } }))
 * ```
 */
export function createZenStackQueryUtils<
  TClient extends AnyNestedClient,
  const S extends SchemaDef,
  const Path extends string,
  const Files extends FileFieldsDef = {},
>(client: TClient, options: ZenStackQueryUtilsOptions<TClient, S, Path, Files>) {
  const {
    schema,
    path,
    files: _files,
    invalidate,
    optimistic,
    live,
    logging,
    auth,
    plugins,
    ...rest
  } = options
  const plugin = zenstackQueryPlugin<TClient>({
    schema,
    path: path === '' ? [] : path.split('.'),
    client,
    invalidate,
    optimistic,
    live,
    logging,
    auth,
  })
  const utils = createTanstackQueryUtils(withTransactionCallbacks(client, schema), {
    ...rest,
    plugins: [plugin, ...(plugins ?? [])],
  } as any)
  PLUGINS.set(utils, plugin)
  return utils as unknown as ApplyTyped<
    RouterUtils<TClient>,
    WithQueryUtils<WithZenStack<S, Path, Files>>
  >
}
