//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema";
import type { FindManyArgs as $FindManyArgs, FindUniqueArgs as $FindUniqueArgs, FindFirstArgs as $FindFirstArgs, ExistsArgs as $ExistsArgs, CreateArgs as $CreateArgs, CreateManyArgs as $CreateManyArgs, CreateManyAndReturnArgs as $CreateManyAndReturnArgs, UpdateArgs as $UpdateArgs, UpdateManyArgs as $UpdateManyArgs, UpdateManyAndReturnArgs as $UpdateManyAndReturnArgs, UpsertArgs as $UpsertArgs, DeleteArgs as $DeleteArgs, DeleteManyArgs as $DeleteManyArgs, CountArgs as $CountArgs, AggregateArgs as $AggregateArgs, GroupByArgs as $GroupByArgs, WhereInput as $WhereInput, SelectInput as $SelectInput, IncludeInput as $IncludeInput, OmitInput as $OmitInput, UncheckedCreateInput as $UncheckedCreateInput, CheckedCreateInput as $CheckedCreateInput, UncheckedUpdateInput as $UncheckedUpdateInput, CheckedUpdateInput as $CheckedUpdateInput, QueryOptions as $QueryOptions } from "@zenstackhq/orm";
import type { SimplifiedPlainResult as $Result, SelectIncludeOmit as $SelectIncludeOmit } from "@zenstackhq/orm";
export type UserFindManyArgs = $FindManyArgs<$Schema, "User">;
export type UserFindUniqueArgs = $FindUniqueArgs<$Schema, "User">;
export type UserFindFirstArgs = $FindFirstArgs<$Schema, "User">;
export type UserExistsArgs = $ExistsArgs<$Schema, "User">;
export type UserCreateArgs = $CreateArgs<$Schema, "User">;
export type UserCreateManyArgs = $CreateManyArgs<$Schema, "User">;
export type UserCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "User">;
export type UserUpdateArgs = $UpdateArgs<$Schema, "User">;
export type UserUpdateManyArgs = $UpdateManyArgs<$Schema, "User">;
export type UserUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "User">;
export type UserUpsertArgs = $UpsertArgs<$Schema, "User">;
export type UserDeleteArgs = $DeleteArgs<$Schema, "User">;
export type UserDeleteManyArgs = $DeleteManyArgs<$Schema, "User">;
export type UserCountArgs = $CountArgs<$Schema, "User">;
export type UserAggregateArgs = $AggregateArgs<$Schema, "User">;
export type UserGroupByArgs = $GroupByArgs<$Schema, "User">;
export type UserWhereInput = $WhereInput<$Schema, "User">;
export type UserSelect = $SelectInput<$Schema, "User">;
export type UserInclude = $IncludeInput<$Schema, "User">;
export type UserOmit = $OmitInput<$Schema, "User">;
export type UserUncheckedCreateInput = $UncheckedCreateInput<$Schema, "User">;
export type UserCheckedCreateInput = $CheckedCreateInput<$Schema, "User">;
export type UserUncheckedUpdateInput = $UncheckedUpdateInput<$Schema, "User">;
export type UserCheckedUpdateInput = $CheckedUpdateInput<$Schema, "User">;
export type UserGetPayload<Args extends $SelectIncludeOmit<$Schema, "User", true>, Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>> = $Result<$Schema, "User", Args, Options>;
export type EmployeeFindManyArgs = $FindManyArgs<$Schema, "Employee">;
export type EmployeeFindUniqueArgs = $FindUniqueArgs<$Schema, "Employee">;
export type EmployeeFindFirstArgs = $FindFirstArgs<$Schema, "Employee">;
export type EmployeeExistsArgs = $ExistsArgs<$Schema, "Employee">;
export type EmployeeCreateArgs = $CreateArgs<$Schema, "Employee">;
export type EmployeeCreateManyArgs = $CreateManyArgs<$Schema, "Employee">;
export type EmployeeCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "Employee">;
export type EmployeeUpdateArgs = $UpdateArgs<$Schema, "Employee">;
export type EmployeeUpdateManyArgs = $UpdateManyArgs<$Schema, "Employee">;
export type EmployeeUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "Employee">;
export type EmployeeUpsertArgs = $UpsertArgs<$Schema, "Employee">;
export type EmployeeDeleteArgs = $DeleteArgs<$Schema, "Employee">;
export type EmployeeDeleteManyArgs = $DeleteManyArgs<$Schema, "Employee">;
export type EmployeeCountArgs = $CountArgs<$Schema, "Employee">;
export type EmployeeAggregateArgs = $AggregateArgs<$Schema, "Employee">;
export type EmployeeGroupByArgs = $GroupByArgs<$Schema, "Employee">;
export type EmployeeWhereInput = $WhereInput<$Schema, "Employee">;
export type EmployeeSelect = $SelectInput<$Schema, "Employee">;
export type EmployeeInclude = $IncludeInput<$Schema, "Employee">;
export type EmployeeOmit = $OmitInput<$Schema, "Employee">;
export type EmployeeUncheckedCreateInput = $UncheckedCreateInput<$Schema, "Employee">;
export type EmployeeCheckedCreateInput = $CheckedCreateInput<$Schema, "Employee">;
export type EmployeeUncheckedUpdateInput = $UncheckedUpdateInput<$Schema, "Employee">;
export type EmployeeCheckedUpdateInput = $CheckedUpdateInput<$Schema, "Employee">;
export type EmployeeGetPayload<Args extends $SelectIncludeOmit<$Schema, "Employee", true>, Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>> = $Result<$Schema, "Employee", Args, Options>;
