// This file is generated by zenstack-orpc. Do not edit.

export const fileFields = {
  "Employee": {
    "contract": {},
    "review": {}
  }
} as const

export type FileFields = typeof fileFields

/** `///` comments of models and fields (OpenAPI descriptions). */
export const docs = {
  "Employee": {
    "fields": {
      "salary": "Read by the employee and HR, changed by HR only.",
      "contract": "Same rules as `salary`.",
      "review": "Written by the employee, read by HR only."
    }
  }
} as const
