import { defineMeta } from '@orpc/server'

/** Metadata attached to every procedure generated by zenstack-orpc. */
export interface ZenStackMeta {
  /** Model name, as declared in ZModel (e.g. `User`). */
  model?: string
  /** ZenStack operation (`findMany`, `update`...), file operation (`upload`...) or `$transaction`/`$changes`. */
  operation: string
  /** For file procedures: the `@file` field. */
  field?: string
}

/**
 * `zenstackMeta(...)` attaches {@link ZenStackMeta} to a procedure, and `getZenStackMeta(procedure)`
 * reads it back, e.g. in a middleware or in a handler `filter`.
 *
 * @example
 * ```ts
 * const readonly = os.middleware(async ({ procedure, next }) => {
 *   const meta = getZenStackMeta(procedure)
 *   if (meta?.model === 'AuditLog' && meta.operation !== 'findMany') throw new ORPCError('FORBIDDEN')
 *   return next()
 * })
 * ```
 */
export const [zenstackMeta, getZenStackMeta] = defineMeta(
  'zenstack',
  (incoming: ZenStackMeta, current: ZenStackMeta | undefined) => ({ ...current, ...incoming }),
)
