import type { AnySchema, JsonSchema, JsonSchemaConverterDirection } from '@orpc/json-schema'
import { ZodToJsonSchemaConverter, type ZodToJsonSchemaConverterOptions } from '@orpc/zod'
import type { SchemaDef } from '@zenstackhq/orm/schema'
import { z } from 'zod'
import type { CrudOperation } from './operations'
import { fieldMeta, modelMeta } from './schema-utils'

/** Zod registry holding named schemas (ZenStack's `ZodSchemaFactory` registry). */
export type SchemaRegistry = z.core.$ZodRegistry<{ id?: string; description?: string }>

const DOC_SCHEMA = Symbol.for('zenstack-orpc.doc-schema')

/**
 * A Standard Schema that documents a value without validating it: used for outputs, which
 * come from the ORM and are trusted (validating large results would only cost time).
 */
export interface DocSchema<T = unknown> {
  readonly '~standard': {
    readonly version: 1
    readonly vendor: 'zenstack-orpc'
    readonly validate: (value: unknown) => { value: T }
  }
  readonly [DOC_SCHEMA]: z.ZodType
}

export function docSchema<T = unknown>(schema: z.ZodType): DocSchema<T> {
  return {
    '~standard': {
      version: 1,
      vendor: 'zenstack-orpc',
      validate: (value) => ({ value: value as T }),
    },
    [DOC_SCHEMA]: schema,
  }
}

/**
 * Validates with `schema` after converting the raw value (e.g. base64 strings to `Bytes`), and
 * is documented as `schema`.
 */
export function preprocessedSchema(schema: z.ZodType, preprocess: (value: unknown) => unknown) {
  return {
    '~standard': {
      version: 1,
      vendor: 'zenstack-orpc',
      validate: (value: unknown) => schema['~standard'].validate(preprocess(value)),
    },
    [DOC_SCHEMA]: schema,
  } as unknown as z.ZodType
}

function isDocSchema(schema: unknown): schema is DocSchema {
  return typeof schema === 'object' && schema !== null && DOC_SCHEMA in schema
}

/**
 * Names or describes a schema in the registry the OpenAPI converter reads (`.describe()` writes to
 * Zod's global registry, which it ignores).
 */
function register<T extends z.ZodType>(
  registry: SchemaRegistry,
  schema: T,
  meta: { id?: string; description?: string },
): T {
  try {
    registry.add(schema, meta)
  } catch {
    // Already registered (or id taken): keep the first registration.
  }
  return schema
}

/** JSON representation of a scalar field in responses (OpenAPI serializer output). */
function scalarSchema(schema: SchemaDef, type: string): z.ZodType {
  switch (type) {
    case 'String':
      return z.string()
    case 'Int':
      return z.number().int()
    case 'Float':
      return z.number()
    case 'Boolean':
      return z.boolean()
    case 'DateTime':
      return z.iso.datetime()
    case 'BigInt':
    case 'Decimal':
      return z.string().describe(`${type}, serialized as a string`)
    case 'Bytes':
      return z.string().describe('Bytes, base64-encoded')
    case 'Json':
      return z.unknown()
    default: {
      const enumDef = schema.enums?.[type]
      if (enumDef) return z.enum(Object.values(enumDef.values) as [string, ...string[]])
      return z.unknown()
    }
  }
}

/**
 * Documentation comments (`///`) of models and fields, generated by the zenstack-orpc ZenStack
 * plugin as `docs` in `orpc.ts` (comments aren't part of the runtime schema).
 */
export type ModelDocs = Readonly<
  Record<
    string,
    { readonly description?: string; readonly fields?: Readonly<Record<string, string>> }
  >
>

function asString(value: unknown): string | undefined {
  return typeof value === 'string' && value !== '' ? value : undefined
}

/** Description of a model: `@@meta('description', ...)`, else its `///` comment. */
export function modelDescription(
  schema: SchemaDef,
  model: string,
  docs?: ModelDocs,
): string | undefined {
  return asString(modelMeta(schema, model, 'description')) ?? asString(docs?.[model]?.description)
}

/** Description of a field: `@meta('description', ...)`, else its `///` comment. */
export function fieldDescription(
  schema: SchemaDef,
  model: string,
  field: string,
  docs?: ModelDocs,
): string | undefined {
  return (
    asString(fieldMeta(schema, model, field, 'description')) ??
    asString(docs?.[model]?.fields?.[field])
  )
}

/**
 * Builds a named response schema per model (`User`, `Post`...): scalar fields, plus relations,
 * present only when requested with `include` / `select`.
 */
export function createModelSchemas(schema: SchemaDef, registry: SchemaRegistry, docs?: ModelDocs) {
  const models = new Map<string, z.ZodObject>()

  for (const [model, modelDef] of Object.entries(schema.models)) {
    const shape: Record<string, z.ZodType> = {}
    for (const [field, fieldDef] of Object.entries(modelDef.fields)) {
      if (fieldDef.relation) {
        const relatedModel = fieldDef.type
        Object.defineProperty(shape, field, {
          enumerable: true,
          get() {
            const related = models.get(relatedModel) as z.ZodType
            const value = fieldDef.array
              ? z.array(related)
              : fieldDef.optional
                ? related.nullable()
                : related
            const description = fieldDescription(schema, model, field, docs)
            return register(registry, value.optional(), {
              description: `${description ? `${description}\n\n` : ''}Present when requested with \`include\` or \`select\``,
            })
          },
        })
        continue
      }
      const scalar = scalarSchema(schema, fieldDef.type)
      let value: z.ZodType = scalar
      if (fieldDef.array) value = z.array(value)
      if (fieldDef.optional) value = value.nullable()
      // The field's description, then its type's (`Bytes, base64-encoded`...).
      const description = [fieldDescription(schema, model, field, docs), scalar.description]
        .filter(Boolean)
        .join('\n\n')
      shape[field] = description ? register(registry, value, { description }) : value
    }
    shape._count = register(registry, z.record(z.string(), z.number().int()).optional(), {
      description: 'Relation counts, when requested with `_count`',
    })
    const description = modelDescription(schema, model, docs)
    models.set(model, register(registry, z.object(shape), { id: model, description }))
  }

  return models
}

/** Documented response of each operation. */
export function operationOutput(model: z.ZodType, op: CrudOperation): z.ZodType {
  switch (op) {
    case 'findMany':
    case 'createManyAndReturn':
    case 'updateManyAndReturn':
      return z.array(model)
    case 'findUnique':
    case 'findFirst':
      return model.nullable()
    case 'exists':
      return z.boolean()
    case 'count':
      return z.union([z.number().int(), z.record(z.string(), z.number().int())])
    case 'aggregate':
      return z.record(z.string(), z.unknown())
    case 'groupBy':
      return z.array(z.record(z.string(), z.unknown()))
    case 'createMany':
    case 'updateMany':
    case 'deleteMany':
      return z.object({ count: z.number().int() })
    default:
      return model
  }
}

const ANONYMOUS_DEF = /^__schema\d+$/
const DEF_PREFIX = '#/$defs/'

/** Names of the `$defs` referenced by `node`. */
function defRefs(node: unknown, refs = new Set<string>()): Set<string> {
  if (Array.isArray(node)) for (const item of node) defRefs(item, refs)
  else if (node && typeof node === 'object') {
    const ref = (node as any).$ref
    if (typeof ref === 'string' && ref.startsWith(DEF_PREFIX))
      refs.add(ref.slice(DEF_PREFIX.length))
    for (const value of Object.values(node)) defRefs(value, refs)
  }
  return refs
}

/**
 * Zod extracts unnamed schemas that are part of a cycle into `$defs` named `__schemaN`. When the
 * cycle goes through a named definition (`PostOrderByWithRelationInput` -> unnamed to-many
 * `orderBy` -> `PostOrderByWithRelationInput`), inlining the unnamed one terminates: do it.
 */
function inlineAnonymousDefs(jsonSchema: unknown, defs: Record<string, any>) {
  const anonymous = Object.keys(defs).filter((name) => ANONYMOUS_DEF.test(name))
  // Anonymous definitions reaching themselves through other anonymous ones stay as they are.
  const reachesItself = (name: string) => {
    const seen = new Set<string>()
    const stack = [...defRefs(defs[name])]
    while (stack.length) {
      const next = stack.pop() as string
      if (next === name) return true
      if (seen.has(next) || !ANONYMOUS_DEF.test(next) || !defs[next]) continue
      seen.add(next)
      stack.push(...defRefs(defs[next]))
    }
    return false
  }
  const inlinable = new Set(anonymous.filter((name) => !reachesItself(name)))
  if (inlinable.size === 0) return
  const inline = (node: any): any => {
    if (Array.isArray(node)) return node.map(inline)
    if (!node || typeof node !== 'object') return node
    const ref = node.$ref
    if (typeof ref === 'string' && inlinable.has(ref.slice(DEF_PREFIX.length))) {
      const { $ref: _, ...rest } = node
      return { ...inline(defs[ref.slice(DEF_PREFIX.length)]), ...rest }
    }
    return Object.fromEntries(Object.entries(node).map(([key, value]) => [key, inline(value)]))
  }
  const inlined = inline(jsonSchema)
  for (const name of inlinable) delete inlined.$defs[name]
  for (const [key, value] of Object.entries(inlined)) (jsonSchema as any)[key] = value
}

/**
 * Removes Zod's anonymous `$defs`: aliases of a named definition (`__schema0: { $ref: '#/$defs/X' }`)
 * are resolved, and unnamed schemas extracted from cycles are inlined when possible.
 */
export function resolveAliasDefs<T extends JsonSchema>(jsonSchema: T): T {
  const defs = (jsonSchema as any)?.$defs as Record<string, any> | undefined
  if (!defs) return jsonSchema
  resolveAliases(jsonSchema, defs)
  inlineAnonymousDefs(jsonSchema, defs)
  return jsonSchema
}

function resolveAliases(jsonSchema: unknown, defs: Record<string, any>) {
  const aliases = new Map<string, string>()
  for (const [name, def] of Object.entries(defs)) {
    if (
      def &&
      typeof def === 'object' &&
      Object.keys(def).length === 1 &&
      typeof def.$ref === 'string'
    ) {
      aliases.set(`#/$defs/${name}`, def.$ref)
    }
  }
  if (aliases.size === 0) return
  const resolve = (ref: string) => {
    let target = ref
    const seen = new Set<string>()
    while (aliases.has(target) && !seen.has(target)) {
      seen.add(target)
      target = aliases.get(target) as string
    }
    return target
  }
  const visit = (node: any) => {
    if (Array.isArray(node)) node.forEach(visit)
    else if (node && typeof node === 'object') {
      if (typeof node.$ref === 'string') node.$ref = resolve(node.$ref)
      for (const value of Object.values(node)) visit(value)
    }
  }
  visit(jsonSchema)
  for (const alias of aliases.keys()) delete defs[alias.slice(DEF_PREFIX.length)]
}

const REGISTRIES = new WeakMap<object, SchemaRegistry>()

export function setRouterRegistry(router: object, registry: SchemaRegistry) {
  REGISTRIES.set(router, registry)
}

/**
 * JSON Schema converter for routers generated by `createZenStackOpenAPIRouter`.
 *
 * ZenStack's input schemas are deeply recursive (`where`, `include`...). This converter reuses
 * their names (`PostWhereInput`, `PostFindManyArgs`...), so the spec references shared
 * components instead of inlining them everywhere: it stays small, readable and fast to generate.
 * It also documents responses.
 *
 * @example
 * ```ts
 * const converter = new ZenStackJsonSchemaConverter(restRouter)
 * new OpenAPIGenerator({ converters: [converter] }).generate(restRouter)
 * ```
 */
export class ZenStackJsonSchemaConverter extends ZodToJsonSchemaConverter {
  constructor(router: object, options: Omit<ZodToJsonSchemaConverterOptions, 'metadata'> = {}) {
    const registry = REGISTRIES.get(router)
    if (!registry) {
      throw new Error(
        'ZenStackJsonSchemaConverter expects a router created by createZenStackOpenAPIRouter',
      )
    }
    super({ cache: true, ...options, metadata: registry as any })
  }

  override condition(
    schema: AnySchema | undefined,
    direction: JsonSchemaConverterDirection,
  ): boolean {
    return isDocSchema(schema) || super.condition(schema, direction)
  }

  override convert(
    schema: AnySchema | undefined,
    direction: JsonSchemaConverterDirection,
  ): [jsonSchema: JsonSchema, optional: boolean] {
    const [jsonSchema, optional] = isDocSchema(schema)
      ? super.convert(schema[DOC_SCHEMA] as unknown as AnySchema, direction)
      : super.convert(schema, direction)
    return [resolveAliasDefs(jsonSchema), optional]
  }
}
