//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema";
import type { ModelResult as $ModelResult } from "@zenstackhq/orm";
export type User = $ModelResult<$Schema, "User">;
export type Session = $ModelResult<$Schema, "Session">;
export type Account = $ModelResult<$Schema, "Account">;
export type Verification = $ModelResult<$Schema, "Verification">;
/**
 * Private todo list: only its owner can see or change a todo.
 */
export type Todo = $ModelResult<$Schema, "Todo">;
/**
 * Public posts: everybody signed in can read published posts, authors manage theirs.
 * Polymorphic (`@@delegate(kind)`): a post is an `Article` or a `Photo`. Shared fields live in
 * the `Post` table, the others in the sub-model's; `post.findMany` returns both kinds, typed as
 * a union narrowed by `kind`. Sub-models inherit the access policies.
 */
export type Post = $ModelResult<$Schema, "Post">;
/**
 * A text post.
 */
export type Article = $ModelResult<$Schema, "Article">;
/**
 * An image with an optional caption.
 */
export type Photo = $ModelResult<$Schema, "Photo">;
/**
 * A chat room: everybody signed in can read it and post in it.
 */
export type Room = $ModelResult<$Schema, "Room">;
/**
 * A chat message: readable by everybody signed in, edited or deleted by its author.
 */
export type Message = $ModelResult<$Schema, "Message">;
