// This file is generated by zenstack-orpc. Do not edit.

export const fileFields = {
  "Photo": {
    "image": {
      "accept": [
        "image/*"
      ],
      "maxSize": 5242880
    }
  }
} as const

export type FileFields = typeof fileFields

/** `///` comments of models and fields (OpenAPI descriptions). */
export const docs = {
  "Todo": {
    "description": "Private todo list: only its owner can see or change a todo.",
    "fields": {
      "post": "Set when archived: the post summing up the archived todos."
    }
  },
  "Post": {
    "description": "Public posts: everybody signed in can read published posts, authors manage theirs.\nPolymorphic (`@@delegate(kind)`): a post is an `Article` or a `Photo`. Shared fields live in\nthe `Post` table, the others in the sub-model's; `post.findMany` returns both kinds, typed as\na union narrowed by `kind`. Sub-models inherit the access policies."
  },
  "Article": {
    "description": "A text post."
  },
  "Photo": {
    "description": "An image with an optional caption."
  },
  "Room": {
    "description": "A chat room: everybody signed in can read it and post in it."
  },
  "Message": {
    "description": "A chat message: readable by everybody signed in, edited or deleted by its author.",
    "fields": {
      "editedAt": "Set when the author edits the message."
    }
  }
} as const
