import fs from 'node:fs'
import path from 'node:path'
import type { CliPlugin } from '@zenstackhq/sdk'
import { getAllFields, getAttributeArg, getLiteral, getLiteralArray } from '@zenstackhq/language/utils'

/**
 * ZenStack CLI plugin.
 *
 * Declared in ZModel with `plugin orpc { provider = '@azzerty23/zenstack-orpc/plugin-orpc' }`, it loads `plugin.zmodel`
 * (the `@file` attribute) and generates `orpc.ts` next to `schema.ts`. That file exposes:
 * - `fileFields`: the `@file` fields, as a const value (attribute names are erased from the
 *   `SchemaDef` types);
 * - `docs`: the `///` comments of models and fields (OpenAPI descriptions), which aren't part of
 *   the runtime schema.
 *
 * Options:
 * - `output`: output directory (defaults to the CLI output directory)
 * - `fileName`: generated file name (defaults to `orpc.ts`)
 */
/** Text of `///` comments. */
function commentText(comments: readonly string[] | undefined): string | undefined {
  const text = (comments ?? [])
    .map((comment) => comment.replace(/^\s*\/*\s?/, ''))
    .join('\n')
    .trim()
  return text === '' ? undefined : text
}

const plugin: CliPlugin = {
  name: 'zenstack-orpc',
  statusText: 'Generating zenstack-orpc metadata',
  generate({ model, defaultOutputPath, pluginOptions }) {
    const docs: Record<string, { description?: string; fields?: Record<string, string> }> = {}
    const fileFields: Record<
      string,
      Record<string, { accept?: string[]; maxSize?: number; multiple?: true }>
    > = {}

    for (const decl of model.declarations) {
      if (decl.$type !== 'DataModel') continue
      const description = commentText((decl as any).comments)
      if (description) docs[decl.name] = { description }
      for (const field of getAllFields(decl as any)) {
        const fieldDescription = commentText(field.comments)
        if (fieldDescription) {
          docs[decl.name] ??= {}
          docs[decl.name].fields ??= {}
          ;(docs[decl.name].fields as Record<string, string>)[field.name] = fieldDescription
        }
        const attr = field.attributes.find((a) => a.decl.$refText === '@file')
        if (!attr) continue
        const accept = getAttributeArg(attr, 'accept')
        const maxSize = getAttributeArg(attr, 'maxSize')
        const config: { accept?: string[]; maxSize?: number; multiple?: true } = {}
        if (accept) config.accept = getLiteralArray<string>(accept)
        if (maxSize) config.maxSize = Number(getLiteral(maxSize))
        if (field.type.array) config.multiple = true
        fileFields[decl.name] ??= {}
        fileFields[decl.name][field.name] = config
      }
    }

    const output =
      typeof pluginOptions.output === 'string' ? pluginOptions.output : defaultOutputPath
    const fileName = typeof pluginOptions.fileName === 'string' ? pluginOptions.fileName : 'orpc.ts'

    const content = [
      '// This file is generated by zenstack-orpc. Do not edit.',
      '',
      `export const fileFields = ${JSON.stringify(fileFields, null, 2)} as const`,
      '',
      'export type FileFields = typeof fileFields',
      '',
      '/** `///` comments of models and fields (OpenAPI descriptions). */',
      `export const docs = ${JSON.stringify(docs, null, 2)} as const`,
      '',
    ].join('\n')

    fs.mkdirSync(output, { recursive: true })
    fs.writeFileSync(path.join(output, fileName), content)
  },
}

export default plugin
