//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema";
import type { FindManyArgs as $FindManyArgs, FindUniqueArgs as $FindUniqueArgs, FindFirstArgs as $FindFirstArgs, ExistsArgs as $ExistsArgs, CreateArgs as $CreateArgs, CreateManyArgs as $CreateManyArgs, CreateManyAndReturnArgs as $CreateManyAndReturnArgs, UpdateArgs as $UpdateArgs, UpdateManyArgs as $UpdateManyArgs, UpdateManyAndReturnArgs as $UpdateManyAndReturnArgs, UpsertArgs as $UpsertArgs, DeleteArgs as $DeleteArgs, DeleteManyArgs as $DeleteManyArgs, CountArgs as $CountArgs, AggregateArgs as $AggregateArgs, GroupByArgs as $GroupByArgs, WhereInput as $WhereInput, SelectInput as $SelectInput, IncludeInput as $IncludeInput, OmitInput as $OmitInput, UncheckedCreateInput as $UncheckedCreateInput, CheckedCreateInput as $CheckedCreateInput, UncheckedUpdateInput as $UncheckedUpdateInput, CheckedUpdateInput as $CheckedUpdateInput, QueryOptions as $QueryOptions } from "@zenstackhq/orm";
import type { SimplifiedPlainResult as $Result, SelectIncludeOmit as $SelectIncludeOmit } from "@zenstackhq/orm";
export type AuthorFindManyArgs = $FindManyArgs<$Schema, "Author">;
export type AuthorFindUniqueArgs = $FindUniqueArgs<$Schema, "Author">;
export type AuthorFindFirstArgs = $FindFirstArgs<$Schema, "Author">;
export type AuthorExistsArgs = $ExistsArgs<$Schema, "Author">;
export type AuthorCreateArgs = $CreateArgs<$Schema, "Author">;
export type AuthorCreateManyArgs = $CreateManyArgs<$Schema, "Author">;
export type AuthorCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "Author">;
export type AuthorUpdateArgs = $UpdateArgs<$Schema, "Author">;
export type AuthorUpdateManyArgs = $UpdateManyArgs<$Schema, "Author">;
export type AuthorUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "Author">;
export type AuthorUpsertArgs = $UpsertArgs<$Schema, "Author">;
export type AuthorDeleteArgs = $DeleteArgs<$Schema, "Author">;
export type AuthorDeleteManyArgs = $DeleteManyArgs<$Schema, "Author">;
export type AuthorCountArgs = $CountArgs<$Schema, "Author">;
export type AuthorAggregateArgs = $AggregateArgs<$Schema, "Author">;
export type AuthorGroupByArgs = $GroupByArgs<$Schema, "Author">;
export type AuthorWhereInput = $WhereInput<$Schema, "Author">;
export type AuthorSelect = $SelectInput<$Schema, "Author">;
export type AuthorInclude = $IncludeInput<$Schema, "Author">;
export type AuthorOmit = $OmitInput<$Schema, "Author">;
export type AuthorUncheckedCreateInput = $UncheckedCreateInput<$Schema, "Author">;
export type AuthorCheckedCreateInput = $CheckedCreateInput<$Schema, "Author">;
export type AuthorUncheckedUpdateInput = $UncheckedUpdateInput<$Schema, "Author">;
export type AuthorCheckedUpdateInput = $CheckedUpdateInput<$Schema, "Author">;
export type AuthorGetPayload<Args extends $SelectIncludeOmit<$Schema, "Author", true>, Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>> = $Result<$Schema, "Author", Args, Options>;
export type ArticleFindManyArgs = $FindManyArgs<$Schema, "Article">;
export type ArticleFindUniqueArgs = $FindUniqueArgs<$Schema, "Article">;
export type ArticleFindFirstArgs = $FindFirstArgs<$Schema, "Article">;
export type ArticleExistsArgs = $ExistsArgs<$Schema, "Article">;
export type ArticleCreateArgs = $CreateArgs<$Schema, "Article">;
export type ArticleCreateManyArgs = $CreateManyArgs<$Schema, "Article">;
export type ArticleCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "Article">;
export type ArticleUpdateArgs = $UpdateArgs<$Schema, "Article">;
export type ArticleUpdateManyArgs = $UpdateManyArgs<$Schema, "Article">;
export type ArticleUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "Article">;
export type ArticleUpsertArgs = $UpsertArgs<$Schema, "Article">;
export type ArticleDeleteArgs = $DeleteArgs<$Schema, "Article">;
export type ArticleDeleteManyArgs = $DeleteManyArgs<$Schema, "Article">;
export type ArticleCountArgs = $CountArgs<$Schema, "Article">;
export type ArticleAggregateArgs = $AggregateArgs<$Schema, "Article">;
export type ArticleGroupByArgs = $GroupByArgs<$Schema, "Article">;
export type ArticleWhereInput = $WhereInput<$Schema, "Article">;
export type ArticleSelect = $SelectInput<$Schema, "Article">;
export type ArticleInclude = $IncludeInput<$Schema, "Article">;
export type ArticleOmit = $OmitInput<$Schema, "Article">;
export type ArticleUncheckedCreateInput = $UncheckedCreateInput<$Schema, "Article">;
export type ArticleCheckedCreateInput = $CheckedCreateInput<$Schema, "Article">;
export type ArticleUncheckedUpdateInput = $UncheckedUpdateInput<$Schema, "Article">;
export type ArticleCheckedUpdateInput = $CheckedUpdateInput<$Schema, "Article">;
export type ArticleGetPayload<Args extends $SelectIncludeOmit<$Schema, "Article", true>, Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>> = $Result<$Schema, "Article", Args, Options>;
