// This file is generated by zenstack-orpc. Do not edit.

export const fileFields = {} as const

export type FileFields = typeof fileFields

/** `///` comments of models and fields (OpenAPI descriptions). */
export const docs = {} as const
