//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema";
import type { ModelResult as $ModelResult } from "@zenstackhq/orm";
export type M0 = $ModelResult<$Schema, "M0">;
export type M1 = $ModelResult<$Schema, "M1">;
export type M2 = $ModelResult<$Schema, "M2">;
export type M3 = $ModelResult<$Schema, "M3">;
export type M4 = $ModelResult<$Schema, "M4">;
export type M5 = $ModelResult<$Schema, "M5">;
export type M6 = $ModelResult<$Schema, "M6">;
export type M7 = $ModelResult<$Schema, "M7">;
export type M8 = $ModelResult<$Schema, "M8">;
export type M9 = $ModelResult<$Schema, "M9">;
export type M10 = $ModelResult<$Schema, "M10">;
export type M11 = $ModelResult<$Schema, "M11">;
export type M12 = $ModelResult<$Schema, "M12">;
export type M13 = $ModelResult<$Schema, "M13">;
export type M14 = $ModelResult<$Schema, "M14">;
export type M15 = $ModelResult<$Schema, "M15">;
export type M16 = $ModelResult<$Schema, "M16">;
export type M17 = $ModelResult<$Schema, "M17">;
export type M18 = $ModelResult<$Schema, "M18">;
export type M19 = $ModelResult<$Schema, "M19">;
export type M20 = $ModelResult<$Schema, "M20">;
export type M21 = $ModelResult<$Schema, "M21">;
export type M22 = $ModelResult<$Schema, "M22">;
export type M23 = $ModelResult<$Schema, "M23">;
export type M24 = $ModelResult<$Schema, "M24">;
export type M25 = $ModelResult<$Schema, "M25">;
export type M26 = $ModelResult<$Schema, "M26">;
export type M27 = $ModelResult<$Schema, "M27">;
export type M28 = $ModelResult<$Schema, "M28">;
export type M29 = $ModelResult<$Schema, "M29">;
export type M30 = $ModelResult<$Schema, "M30">;
export type M31 = $ModelResult<$Schema, "M31">;
export type M32 = $ModelResult<$Schema, "M32">;
export type M33 = $ModelResult<$Schema, "M33">;
export type M34 = $ModelResult<$Schema, "M34">;
export type M35 = $ModelResult<$Schema, "M35">;
export type M36 = $ModelResult<$Schema, "M36">;
export type M37 = $ModelResult<$Schema, "M37">;
export type M38 = $ModelResult<$Schema, "M38">;
export type M39 = $ModelResult<$Schema, "M39">;
export type Tag = $ModelResult<$Schema, "Tag">;
