import type { AnyNestedClient, Client, InferClientContext } from '@orpc/client'
import type { SchemaDef } from '@zenstackhq/orm/schema'
import type { FileFieldsDef } from '../files/schema'
import type { ZenStackRouterUtils } from '../tanstack-query/types'
import { withTransactionCallbacks } from '../transaction-callback'
import type { ApplyAtPath, GetAtPath, ZenStackRouterClient } from '../types/client'

export { type TransactionRef, txRef } from '../transaction-ref'
export type * from '../types/client'
export type { DefaultOperationResult, OperationArgs, OperationResult } from '../types/operations'
export type { WithOptimistic, ZenDefaultResult, ZenResult } from '../types/result'
export {
  isZenStackError,
  type ZenStackError,
  type ZenStackErrorData,
  type ZenStackErrorReason,
} from './errors'

/**
 * Describes where a ZenStack router lives in your app router.
 *
 * @example `WithZenStack<SchemaType, 'db', FileFields>` for `router = { db: createZenStackRouter(...) }`
 */
export interface WithZenStack<S extends SchemaDef, Path extends string = '', Files = {}> {
  readonly __schema: S
  readonly __path: Path
  readonly __files: Files
}

/** Typing descriptor applied by {@link typedClient}: `WithClient<Z>` or `WithQueryUtils<Z>`. */
export interface TypedDescriptor {
  readonly __kind: 'client' | 'query-utils'
  readonly __zenstack: WithZenStack<any, any, any>
}

/** Types an oRPC client (`createORPCClient`) with inferred ZenStack results. */
export interface WithClient<Z extends WithZenStack<any, any, any>> extends TypedDescriptor {
  readonly __kind: 'client'
  readonly __zenstack: Z
}

type ContextAt<TClient, P extends string> =
  GetAtPath<TClient, P> extends AnyNestedClient ? InferClientContext<GetAtPath<TClient, P>> : object

/** Result of applying a descriptor to a client (or to TanStack Query utils). */
export type ApplyTyped<TClient, T extends TypedDescriptor> =
  T['__zenstack'] extends WithZenStack<infer S, infer P, infer F>
    ? T['__kind'] extends 'client'
      ? ApplyAtPath<TClient, P, ZenStackRouterClient<S, ContextAt<TClient, P>, F>>
      : ApplyAtPath<TClient, P, ZenStackRouterUtils<S, UtilsContextAt<TClient, P>, F>>
    : never

type UtilsContextAt<TUtils, P extends string> =
  GetAtPath<TUtils, P> extends {
    $transaction: { call: Client<infer C, any, any, any> }
  }
    ? C
    : object

/**
 * Applies composable types to a client. At runtime, only lets `$transaction` take a callback
 * (model keys are capitalized to get model names: prefer {@link createZenStackClient} if a model
 * name doesn't start with an uppercase letter).
 *
 * @example
 * ```ts
 * type Zen = WithZenStack<SchemaType, 'db', FileFields>
 * export const client = typedClient<WithClient<Zen>>()(createORPCClient<AppRouterClient>(link))
 * ```
 */
export function typedClient<T extends TypedDescriptor>() {
  return <TClient>(client: TClient): ApplyTyped<TClient, T> =>
    withTransactionCallbacks(client) as ApplyTyped<TClient, T>
}

export interface ZenStackClientOptions<S extends SchemaDef, Path extends string, Files> {
  /** The ZenStack schema (`schema` from the generated `schema.ts`). */
  schema: S
  /** Where the ZenStack router is mounted in the app router (dotted for nested routers). */
  path: Path
  /** `fileFields` from the `orpc.ts` file generated by the zenstack-orpc ZenStack plugin. */
  files?: Files
}

/**
 * Types an oRPC client so ZenStack procedures infer their results from `select` / `include` /
 * `omit`, and lets `$transaction` take a callback.
 *
 * @example
 * ```ts
 * export const client = createZenStackClient(createORPCClient<AppRouterClient>(link), {
 *   schema, path: 'db', files: fileFields,
 * })
 * const posts = await client.db.post.findMany({ include: { author: true } })
 * ```
 */
export function createZenStackClient<
  TClient,
  const S extends SchemaDef,
  const Path extends string,
  const Files extends FileFieldsDef = {},
>(client: TClient, options: ZenStackClientOptions<S, Path, Files>) {
  return withTransactionCallbacks(client, options.schema) as ApplyTyped<
    TClient,
    WithClient<WithZenStack<S, Path, Files>>
  >
}
